name: Translate Readme

on:
  push:
    branches: [ "main" ]

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run translation
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          langs: "zh"
          provider: "g4f" # Usa un proveedor gratuito para evitar el error de la API de OpenAI
